import pandas as pd
import numpy as np
import os
import joblib
import urllib.request
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

def main():
    # The script is executed from \models\, so look backward into \data\
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    data_dir = os.path.join(base_dir, "data")
    
    print("Loading FMD tabular datasets...")
    train_df = pd.read_csv(os.path.join(data_dir, "train.csv"))
    test_df = pd.read_csv(os.path.join(data_dir, "test.csv"))
    
    # Drop index artifacts natively generated by csv saving
    if "Unnamed: 0" in train_df.columns:
        train_df = train_df.drop(columns=["Unnamed: 0"])
    if "Unnamed: 0" in test_df.columns:
        test_df = test_df.drop(columns=["Unnamed: 0"])
        
    print(f"Train Shape: {train_df.shape}")
    print(f"Test Shape:  {test_df.shape}")
    
    target_col = 'class' if 'class' in train_df.columns else 'label'
    
    X_train = train_df.drop(columns=[target_col])
    y_train = train_df[target_col]
    X_test = test_df.drop(columns=[target_col])
    y_test = test_df[target_col]
    
    print(f"\nTraining Random Forest Classifer (100 Trees, Balanced Classes)...")
    rf_model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1, class_weight='balanced')
    rf_model.fit(X_train, y_train)
    
    print("Training Complete! Evaluating on unseen Test Set...")
    y_pred = rf_model.predict(X_test)
    
    acc = accuracy_score(y_test, y_pred)
    print(f"\n=============================")
    print(f"Final Identifcation Accuracy: {acc:.4f}")
    print(f"=============================\n")
    print("Detailed Signature Fingerprinting Report:")
    print(classification_report(y_test, y_pred))
    
    # Save the model directly into the models folder next to this script
    current_dir = os.path.dirname(os.path.abspath(__file__))
    model_path = os.path.join(current_dir, "rf_polymer_classifier.pkl")
    joblib.dump(rf_model, model_path)
    print(f"\nModel strictly serialized and saved to {model_path} for your Stage 4 pipeline!")

if __name__ == "__main__":
    main()
